INSERT INTO users (name, email, role, password) VALUES ('Aditya. T.Y', 'aditya.trikuncoro12@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Ainun. M.', 'ainunmardiyah703@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Aleksandra. Y.R.O.', 'aleksandraole974@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Alfian. N.R.', 'nramzie@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Andine. S.B.', 'andinesantika8@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Catur. W.', 'caturwulandari528@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Dhienisa. R.', 'dhienisaarahmadianti@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Dimas. A.H.', 'dimasarya240502@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Dyah. A.N.S.', 'dyahayunovitasari1@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Fajar. A.', 'fajaralfandi2002@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Faradhiba. B.Q.A', 'faradhibaqurotaayun@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Gita. D.P.A.', 'gitadwiputri06@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Hanief. M.', 'haniefmuslimah5@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Juwandi', 'juwandinasir072@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Lalu. A.A.Y.', 'arinalyusran@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Mahardhika. R.S.', 'mahardhikaputri0@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Mario. S.R.', 'mariorifai48@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Mawar. I.', 'mawarislamiati10@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('M. Faruq. A.', 'mfaruqal01@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Nanda. Y.T.M.', 'nandayekti12@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Nur. L.K.W.', 'kusumawardaninurlaeli@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Nurcholis. I.', 'kholisindrawan@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Rio. N.', 'rionugroho1607@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Rizqi. I.P.', 'intan.rahayu0412@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Septhia. V.I.', 'septhiaviolitaisma@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Viona. C.A.C.', 'vionacornelia01@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Wahyu. K.', 'wahyukur160102@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Yasmina. F.P.', 'thataprmt79@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('A Sirojuddin Hakim', 'ahmhaks19@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Ade Rizal Rusvian Daffa', 'aderizalrusviandaffa18@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Adelia Hesa Yasmila', 'hesayasmila@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Akhmad Sandy Wahyu Pratama', 'akhmad_wahyu@gmail.com', 'Mahasiswa', 'password');
INSERT INTO users (name, email, role, password) VALUES ('Antika Yuniar Saputri', 'antikayuni41@gmail.com', 'Mahasiswa', 'password');